# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl:

# Title of the Site
title: RabiChora's Portfolio
# Description of the Site
description: Personal Portfolio
# URL of Image of the Site
site-image: /assets/images/Front-self.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: https://z3.ax1x.com/2021/11/24/oCeYlV.png

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://z3.ax1x.com/2021/11/23/o9RxTf.jpg
# https://i.imgur.com/JUtIYjF.jpg
# https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
social-page-img: https://z3.ax1x.com/2021/11/23/o9WF6s.gif
# If you don't want to use any icon, you can leave them blank.
email: charlotte_li_19990615@outlook.com
facebook_username: 100006446536044
twitter_username: RabiChora
instagram_username: charlotttte.liiii
linkedin_username: yangyuqing-li-652890198
github_username:  RabiChora
# youtube_channel_id: UCk_93NXYP-U_AOB5GfWlOow
# reddit_username: / 
# behance_username: /
# dribbble_username: /
# spotify_username: /

# Google Analytics
# google-analytics: UA-163806439-1

# Disqus
disqus-shortname: RabiChora

# Name of the Author
author-name: RabiChora[Yangyuqing(Charlotte) Li]
# URL for the Image of the Author
author-image: https://z3.ax1x.com/2021/11/23/o9Rv0P.jpg
# 60 Words About the Author
author-about: Undergraduate from Oxford University with a degree on Mathematics and Computer Science. Passionate about Tech Art, specifically in areas of rendering and tools making for DCC softwares.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/RabiChora

# Image of CV
cv-image: https://z3.ax1x.com/2021/11/23/o925GQ.png
  # https://i.imgur.com/ALJuy2P.png
  # https://z3.ax1x.com/2021/11/23/o925GQ.png
  # https://i.loli.net/2021/11/23/cULpSb9eNF6aZf2.png


# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'works'
    values:
      layout: works
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'cv'
    values:
      layout: cv


# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
